index:
    path: /
    controller: App\Controller\HomeController::index
    
viewerModeSearch:
    path: /viewerModeSearch
    controller: App\Controller\ViewerModeController::search 
viewerModeFind:
    path: /viewerModeFindByCategory
    controller: App\Controller\ViewerModeController::findByCategory     

viewerModeMessages:
    path: /viewerModeMessages
    controller: App\Controller\ViewerModeController::messages
viewerModeMessagesRequest:
    path: /viewerModeMessages/requestMeeting
    controller: App\Controller\ViewerModeController::requestMeeting   
viewerModeViewRequestMeeting:
    path: /viewerModeMessages/viewRequestMeeting
    controller: App\Controller\ViewerModeController::viewRequestMeeting 
viewerModeMessagesCreate:  
    path: /viewerModeMessages/createMessage
    controller: App\Controller\ViewerModeController::createMessage 


viewerModeEvents:
    path: /viewerModeEvents
    controller: App\Controller\ViewerModeController::events               
viewerModeEvents_eventId:
    path: /viewerModeEvents/eventLiveId
    controller: App\Controller\ViewerModeController::eventLiveId
viewerModeEvents_eventUpId:
    path: /viewerModeEvents/eventUpcomingId
    controller: App\Controller\ViewerModeController::eventUpcomingId   
viewerModeEvents_eventVideoId:
    path: /viewerModeEvents/eventVideoId
    controller: App\Controller\ViewerModeController::eventVideoId 

viewerModeInfluencerProfil:
    path: /viewerModeInfluencerProfil/id
    controller: App\Controller\ViewerModeController::influencerProfil 

viewerModeChat:
    path: /viewerModeChat/id
    controller: App\Controller\ViewerModeController::chat 



