index:
    path: /
    controller: App\Controller\HomeController::index
    
viewerModeSearch:
    path: /viewerModeSearch
    controller: App\Controller\ViewerModeController::search  
viewerModeEvents:
    path: /viewerModeEvents
    controller: App\Controller\ViewerModeController::events    
viewerModeMessages:
    path: /viewerModeMessages
    controller: App\Controller\ViewerModeController::messages            
viewerModeEvents_eventId:
    path: /viewerModeEvents/eventId
    controller: App\Controller\ViewerModeController::eventId
